cluster:
  mkdir -p logs/{rule} &&
  sbatch --parsable
    --partition={resources.partition}
    --qos={resources.qos}
    --cpus-per-task={resources.cpus_per_task}
    --mem={resources.mem}
    --time={resources.time}
    --job-name=smk-{rule}
    --output=logs/{rule}/%j-%u-{rule}.out
default-resources:
  - account=zhzhang_gibh
  - partition=cv2
  - qos=normal
  - time="4:0:0"
  - mem="4G"
  - cpus_per_task=1

scheduler: greedy
use-conda: False
local-cores: 1
keep-going: False
latency-wait: 60
restart-times: 0
printshellcmds: True
cluster-cancel: "scancel"
cluster-status: "slurm-status"
rerun-incomplete: True
max-jobs-per-second: 10
max-status-checks-per-second: 1
